# Generated by Django 4.2.3 on 2023-08-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
